### ISSUE TITLE
Add solvuu_build in generated merlin file

### ISSUE THREAD

**Issue by pveber** [solvuu/solvuu_build#11]
This would avoid merlin complaining when we edit the project description

**Comment by agarwal** [comment]
@pveber It seems this was already done in 19f1f8c36dab6ffbbca3dbb69696efd5dcfaf7c1, prior to this issue being created. Please close the issue if I'm right.

**Comment by agarwal** [comment]
I also added solvuu_build to the generated .ocamlinit file. Closing this issue.
