### ISSUE TITLE
-safe-string should be optional

### ISSUE THREAD

**Issue by pveber** [solvuu/solvuu_build#8]
It seems it is  not possible to use `camlzip` and `-safe-string` at the same time. What about making this option optional? If so, what should be the API?

**Comment by agarwal** [comment]
Yes, definitely needs to be optional. One question I have is how libraries with and without this option interact.

> what should be the API?

We really need to change the whole API as discussed offline. Then making this particular option optional shouldn't be hard.

**Comment by pveber** [comment]
>We really need to change the whole API as discussed offline. Then making this particular option optional >shouldn't be hard.

Ok then let's keep this issue open till we actually change the API. In the mean time I used the following workaround for `biocaml`:
```ocaml
module Project = struct
  let name = "biocaml"
[...]
end

module Base =  Make(Project)

let plugin = function
  | Before_options ->
    Base.plugin Before_options ;
    Ocamlbuild_pack.Configuration.parse_string "true: -safe_string"
  | x -> Base.plugin x

let () = dispatch plugin
```
I'm not saying that I'm proud of it, but it works!

**Comment by agarwal** [comment]
Done in 904b1b9822d2f3e59862db37bf5205f0aaf05a02.
