### ISSUE TITLE
Installation of a library/app should be optional

### ISSUE THREAD

**Issue by pveber** [solvuu/solvuu_build#9]
If we have a library or app for tests/benchmarks, in general we'd rather not install it. We miss a flag in an item description to prevent installation.

**Comment by agarwal** [comment]
I propose we remove the `build_if` property of libs and apps. A solvuu_build plugin already has to explicitly provide the list of libs and apps, so end users can easily filter this list themselves. That is more flexible, and our current solution is already kind of wrong.

We allow the option of building only if _all_ packages of a lib or app are installed, but in practice there are just some that are optional (lwt and async). It should be a build bug if the others aren't installed.

**Comment by agarwal** [comment]
I've removed `build_if` (0bb660826d91fef98acfca85633a90778905230f), and have provided `dep_opts_sat` (037287b9e1cc729f122bb2337368cbe6bea012cc) as a convenience function for end users. For example, in biocaml, we can just do this now:

```ocaml
let optional_pkgs = ["async"; "lwt"]

let items =
  [unix; async; lwt; ez; benchmark; test; run_benchmarks; run_tests]
  |> List.filter ~f:(fun x -> Project.dep_opts_sat x optional_pkgs)
```

This seems strictly better, so closing this issue. @pveber Please reopen if you want to discuss further.
